<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-02-23 15:32

$extensionPath = t3lib_extMgm::extPath('irre_workspaces');
$extensionClassesPath = $extensionPath . 'classes/';
return array(
	'tx_irreworkspaces_extdirect_actionhandler' => $extensionClassesPath . 'ExtDirect/ActionHandler.php',
	'tx_irreworkspaces_extdirect_parameterrecord' => $extensionClassesPath . 'ExtDirect/ParameterRecord.php',
	'tx_irreworkspaces_service_tcemainservice' => $extensionClassesPath . 'Service/TceMainService.php',
);
?>