<?php
namespace OliverHader\IrreWorkspaces\Alternative;

/***************************************************************
 * Copyright notice
 *
 * (c) 2012 Oliver Hader <oliver.hader@typo3.org>
 * All rights reserved
 *
 * This script is part of the TYPO3 project. The TYPO3 project is
 * free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * The GNU General Public License can be found at
 * http://www.gnu.org/copyleft/gpl.html.
 * A copy is found in the textfile GPL.txt and important notices to the license
 * from the author is found in LICENSE.txt distributed with these scripts.
 *
 * This script is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * This copyright notice MUST APPEAR in all copies of the script!
 ***************************************************************/

use TYPO3\CMS\Core\DataHandling\DataHandler;

/**
 * @author Oliver Hader <oliver.hader@typo3.org>
 * @package EXT:irre_workspaces
 */
class DataHandlerHook extends \TYPO3\CMS\Version\Hook\DataHandlerHook {

	/**
	 * Send an email notification to users in workspace
	 *
	 * @param array $stat Workspace access array (from t3lib_userauthgroup::checkWorkspace())
	 * @param integer $stageId New Stage number: 0 = editing, 1= just ready for review, 10 = ready for publication, -1 = rejected!
	 * @param string $table Table name of element (or list of element names if $id is zero)
	 * @param integer $id Record uid of element (if zero, then $table is used as reference to element(s) alone)
	 * @param string $comment User comment sent along with action
	 * @param DataHandler $tcemainObj TCEmain object
	 * @param array $notificationAlternativeRecipients List of recipients to notify instead of be_users selected by sys_workspace, list is generated by workspace extension module
	 * @return void
	 */
	protected function notifyStageChange(array $stat, $stageId, $table, $id, $comment, DataHandler $tcemainObj, array $notificationAlternativeRecipients = NULL) {
		if ($notificationAlternativeRecipients === NULL) {
			$notificationAlternativeRecipients = array();
		}

		if (\OliverHader\IrreWorkspaces\Service\ConfigurationService::getInstance()->getEnableAlternativeNotification()) {
			$this->getChangeStageActionService()->notify(
				$stat,
				$stageId,
				$table,
				$id,
				$comment,
				$notificationAlternativeRecipients
			);
		} else {
			parent::notifyStageChange(
				$stat,
				$stageId,
				$table,
				$id,
				$comment,
				$tcemainObj,
				$notificationAlternativeRecipients
			);
		}
	}

	/**
	 * @return \OliverHader\IrreWorkspaces\Service\Action\ChangeStageService
	 */
	protected function getChangeStageActionService() {
		return \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(
			'OliverHader\\IrreWorkspaces\\Service\\Action\\ChangeStageService'
		);
	}

}